### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by natebass** [code4sac/opensac.org#23]
Add Contact page [opensac.org/contact](https://opensac.org/contact).

Figma design is [here](https://www.figma.com/file/attWQWKwed1XSaaaMuzM5m/Open-Sac-Website?type=design&node-id=349-386&mode=design&t=9KFdLi1BmyJcnfK4-0).

### Notes

The page includes a contact form. We can start by implementing the design, but we will need to discuss the URL that this form will submit to.

### Status

- [x]  Code initial design.
- [x]  Mobile design. Note: there is no Figma design for mobile.
- [x]  Implement Material design form. I am checking out this [example](https://codepen.io/llabrie/pen/drevqR).

**Comment by SKYang014** [comment]
Heya, could I get this assigned to me?

**Comment by MonstersInc-sudo** [comment]
I was reviewing the code and had a couple questions. Let me know if I should raise a separate issue.

1.  Looks like in file [src/app/contact/contactSectionMission.jsx](https://github.com/code4sac/opensac.org/blob/main/src/app/contact/contactSectionMission.jsx) that there is a typo. Should be label instead of lable.
2. Is there a plan to implement form validation? May be be done with the material design implementation though.

-MonstersInc-sudo

**Comment by natebass** [comment]
@MonstersInc-sudo Good idea; added here https://github.com/orgs/code4sac/projects/8/views/4. I added it so that we wouldn't forget, but I haven't created an issue yet.

An issue could encompass the entire "finishing steps" on the form, such as the backend where it submits to. There is also a "New members" form to be discussed. That could possibly just be a link to a Google Form.

Closed by #50.
Future improvements can be raised in a separate issue. Started here #47, feel free to add or create a new one.
