### ISSUE TITLE
Website performance profiling

### ISSUE THREAD

**Issue by natebass** [code4sac/opensac.org#48]
Here are some performance issues that we should resolve before the release of version 1. This issue will be updated as needed. Please post any other performance problems in the comments.

- [ ] CSS profiling

### CSS
**Problem** Navigating to different pages is not smooth.
**Solution** Load all CSS in the root layout. [layout.js](https://github.com/code4sac/opensac.org/blob/main/src/app/layout.js)

Each page imports it's own CSS file, which is loaded on each page navigation. When a new stylesheet it loaded, it causes the entire page to re-render. This could cause the page to "flash" and animations to not feel smooth. I want to run some tests to confirm this.

**Comment by natebass** [comment]
### CSS
I see that new CSS is loaded in the devtools network tab each time the page changes. We should look at the "paint" metrics to confirm any performance benefits in fixing this.
![Screenshot from 2023-12-27 16-46-55](https://github.com/code4sac/opensac.org/assets/6665595/b71dd2d2-9239-4f70-b0af-f6c66b231381)

**Comment by nicklisin** [comment]
@natebass Hi! Happy New Year! ) I don't notice any issues with the animation. Could the problem be specific to a particular browser? The site takes a bit longer to load the first time, but after caching, everything runs smoothly.

I can see that when transitioning between pages, an additional CSS chunk is sometimes loaded. Not all styles, just an additional part. These are the styles that were not required for rendering the previous page. Isn't this the expected behavior?
